### ISSUE TITLE
Feature Request: p and P / would love to be able to use vim keys for yank paste etc...

### ISSUE THREAD

**Issue by jrmiller82** [seanyeh/vibreoffice#16]
Would really like to be able to kill some lines (can't remember the correct terminology, I've used so much Emacs and vim that kill, pull, yank, etc are blurred... I think it's yank then put right?) I'd love to be able to D or dd a line and then move and p a line back in. 

OT: I _love_ the plug in though. While I prefer to write in LaTeX when I can, there's just some times that I have to use a WYSIWG for my job. I bounce around between Libre, Pages, and Word depending on the application. But, your plugin is going to have me permanently switching to Libre for just about everything. 

Now to find time to learn how this program is coded to send you a few pulls.

**Comment by seanyeh** [comment]
Thanks for your interest in my project! It's still very new and I've been pretty busy so a lot of fundamental features are missing. If you need any guidance with the code, don't hesitate to ask. My gut feeling with how to approach this problem is to find where all deletions happen and create a common call to a function which stores the selected text to a global buffer string (or if you want to implement buffer registers, then..... good luck!).

**Comment by seanyeh** [comment]
Just added yank (y) and paste (p,P) using the system clipboard (not yank registers like in vim). I hope they work
