### ISSUE TITLE
"p" not working

### ISSUE THREAD

**Issue by titouancreach** [seanyeh/vibreoffice#22]
I've installed the plugin for libreoffice 4.4 (in french langage). Unfortunately, `p` (for past) doesn't work. If I copy a line using `yy` or `dd`, and I press `p` after, nothing happens.

**Comment by seanyeh** [comment]
Thanks for trying out vibreoffice. It is a new project and a lot of essential features are not implemented yet, including paste. This is a duplicate of https://github.com/seanyeh/vibreoffice/issues/16
Let me know if you're interested in contributing, otherwise I will try to get to it when I have time (probably next month)
